# Generated by Django 5.2.13 on 2026-04-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('favorite_team', models.CharField(blank=True, max_length=100)),
                ('favorite_player', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
        migrations.CreateModel(
            name='FanStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_watched', models.IntegerField(default=0)),
                ('reactions_count', models.IntegerField(default=0)),
                ('chat_messages_count', models.IntegerField(default=0)),
                ('ai_interactions_count', models.IntegerField(default=0)),
                ('fan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='fans.fanprofile')),
            ],
        ),
    ]
