# Generated by Django 5.2.13 on 2026-04-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=200, unique=True)),
                ('match_title', models.CharField(max_length=300)),
                ('team1_name', models.CharField(max_length=100)),
                ('team1_score', models.CharField(blank=True, max_length=50)),
                ('team2_name', models.CharField(max_length=100)),
                ('team2_score', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='live', max_length=50)),
                ('batting_scorecard', models.JSONField(blank=True, default=dict)),
                ('bowling_scorecard', models.JSONField(blank=True, default=dict)),
                ('raw_html', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overs', models.CharField(max_length=10)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('economy', models.FloatField()),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowlers', to='scorecard.scorecardcache')),
            ],
        ),
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('runs', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=50)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batsmen', to='scorecard.scorecardcache')),
            ],
        ),
    ]
