# Generated by Django 5.2.13 on 2026-04-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('champion', models.CharField(max_length=100)),
                ('runner_up', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('venues', models.IntegerField()),
                ('teams', models.IntegerField(default=8)),
                ('half_centuries', models.IntegerField(default=0)),
                ('centuries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SeasonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orange_cap_player', models.CharField(max_length=100)),
                ('orange_cap_team', models.CharField(max_length=100)),
                ('orange_cap_runs', models.IntegerField()),
                ('purple_cap_player', models.CharField(max_length=100)),
                ('purple_cap_team', models.CharField(max_length=100)),
                ('purple_cap_wickets', models.IntegerField()),
                ('most_fours_player', models.CharField(max_length=100)),
                ('most_fours_team', models.CharField(max_length=100)),
                ('most_fours_count', models.IntegerField()),
                ('most_sixes_player', models.CharField(max_length=100)),
                ('most_sixes_team', models.CharField(max_length=100)),
                ('most_sixes_count', models.IntegerField()),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='history.season')),
            ],
        ),
    ]
