# Generated by Django 5.2.13 on 2026-04-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricapi_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('venue', models.CharField(max_length=200)),
                ('match_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('team1_score', models.CharField(blank=True, max_length=50)),
                ('team2_score', models.CharField(blank=True, max_length=50)),
                ('team1_overs', models.CharField(blank=True, max_length=20)),
                ('team2_overs', models.CharField(blank=True, max_length=20)),
                ('result', models.TextField(blank=True)),
                ('last_ball_event', models.CharField(blank=True, max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('color_primary', models.CharField(default='#1a1a2e', max_length=7)),
                ('color_secondary', models.CharField(default='#FFD700', max_length=7)),
                ('logo_emoji', models.CharField(default='🏏', max_length=10)),
                ('home_ground', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('fire', '🔥'), ('six', '6️⃣'), ('wicket', '🎯'), ('heart', '❤️'), ('wow', '😮'), ('sad', '😢')], max_length=20)),
                ('username', models.CharField(default='Anonymous', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='matches.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='matches.team'),
        ),
    ]
